[project]
name = 'verbose_contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.container_with_owner_transfer]
path = 'contracts/container_with_owner_transfer.clar'
clarity_version = 2
epoch = 2.5

[contracts.file_rating]
path = 'contracts/file_rating.clar'
clarity_version = 2
epoch = 2.5

[contracts.immutable_storage]
path = 'contracts/immutable_storage.clar'
clarity_version = 2
epoch = 2.5

[contracts.multi_send_with_pause_functionality]
path = 'contracts/multi_send_with_pause_functionality.clar'
clarity_version = 2
epoch = 2.5

[contracts.result_finalization]
path = 'contracts/result_finalization.clar'
clarity_version = 2
epoch = 2.5

[contracts.withdrawal_cooldown_wallet]
path = 'contracts/withdrawal_cooldown_wallet.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
