[project]
name = 'verbose_contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.container_with_owner_transfer]
path = 'contracts/container_with_owner_transfer.clar'
clarity_version = 2
epoch = 2.5

[contracts.file_rating]
path = 'contracts/file_rating.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
